# Generated by Django 2.1.13 on 2019-10-18 04:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 18, 4, 12, 32, 954724))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 18, 4, 12, 32, 954749))),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=255)),
                ('district_id', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 18, 4, 12, 32, 954064))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 18, 4, 12, 32, 954089))),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_name', models.CharField(max_length=255)),
                ('lang_code', models.CharField(max_length=150)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 18, 4, 12, 32, 952868))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 18, 4, 12, 32, 952902))),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loyalty_type', models.CharField(max_length=255)),
                ('loyalty_point', models.IntegerField()),
                ('conversion', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 18, 4, 12, 32, 966711))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 18, 4, 12, 32, 966738))),
            ],
        ),
        migrations.CreateModel(
            name='ManageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_eng', models.CharField(max_length=255)),
                ('title_hnd', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 10, 18, 4, 12, 32, 959371))),
                ('contains_eng', models.TextField()),
                ('contains_hnd', models.TextField()),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 18, 4, 12, 32, 959657))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 18, 4, 12, 32, 959682))),
                ('feature_image', models.ImageField(blank=True, upload_to='media')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.District')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='MobileLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_id', models.IntegerField()),
                ('lang_key', models.CharField(max_length=255)),
                ('lang_lab', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 18, 4, 12, 32, 964344))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 18, 4, 12, 32, 964369))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_eng', models.TextField()),
                ('message_hnd', models.TextField()),
                ('sms_status', models.IntegerField(default=0)),
                ('push_status', models.IntegerField(default=0)),
                ('sms_request', models.TextField()),
                ('push_request', models.TextField()),
                ('sms_response', models.TextField()),
                ('push_response', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 18, 4, 12, 32, 960986))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 18, 4, 12, 32, 961012))),
                ('status', models.IntegerField(default=1)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.District')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 18, 4, 12, 32, 958724))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 18, 4, 12, 32, 958750))),
                ('user_id_farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
                ('user_id_retailer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProductsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.IntegerField()),
                ('product_price', models.FloatField()),
                ('product_total_price', models.FloatField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 18, 4, 12, 32, 965928))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 18, 4, 12, 32, 965953))),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_code', models.CharField(max_length=100)),
                ('product_unit', models.CharField(max_length=10)),
                ('product_price', models.FloatField(blank=True, null=True)),
                ('product_image', models.ImageField(blank=True, upload_to='media')),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 18, 4, 12, 32, 957856))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 18, 4, 12, 32, 957885))),
            ],
        ),
        migrations.CreateModel(
            name='Recharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=255)),
                ('transation_id', models.IntegerField()),
                ('transation_request', models.TextField()),
                ('transation_response', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 18, 4, 12, 32, 963486))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 18, 4, 12, 32, 963513))),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.Order')),
                ('user_id_farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user_auth_recharge', to=settings.AUTH_USER_MODEL)),
                ('user_id_retailer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user_auth_recharge', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scratch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 18, 4, 12, 32, 965098))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 18, 4, 12, 32, 965123))),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.Order')),
                ('user_id_farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user_auth', to=settings.AUTH_USER_MODEL)),
                ('user_id_retailer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user_auth', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 18, 4, 12, 32, 953519))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 18, 4, 12, 32, 953548))),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('query', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 18, 4, 12, 32, 961938))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 18, 4, 12, 32, 961964))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupportReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('query', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 18, 4, 12, 32, 962691))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 18, 4, 12, 32, 962717))),
                ('support_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.Support')),
                ('user_id_admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLoyaltyPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_user_id', models.IntegerField()),
                ('from_user_id', models.IntegerField()),
                ('loyalty_type', models.CharField(max_length=255)),
                ('loyalty_points_id', models.CharField(max_length=255)),
                ('order_id', models.IntegerField()),
                ('loyalty_point', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 18, 4, 12, 32, 967609))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 18, 4, 12, 32, 967637))),
                ('status', models.IntegerField(default=1)),
                ('user_id_farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user_auth_point', to=settings.AUTH_USER_MODEL)),
                ('user_id_retailer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user_auth_point', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField()),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('aadhar_no', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('user_photo', models.ImageField(blank=True, upload_to='media')),
                ('aadhar_card', models.ImageField(blank=True, upload_to='media')),
                ('pan_card', models.ImageField(blank=True, upload_to='media')),
                ('vote_id', models.ImageField(blank=True, upload_to='media')),
                ('soil_card', models.ImageField(blank=True, upload_to='media')),
                ('fertilizer_photo', models.ImageField(blank=True, upload_to='media')),
                ('land_area', models.CharField(blank=True, max_length=255, null=True)),
                ('otp', models.CharField(blank=True, max_length=10, null=True)),
                ('fcm_id', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 18, 4, 12, 32, 955748))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 18, 4, 12, 32, 955775))),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.District')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.Language')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.State')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.AddField(
            model_name='orderproductsdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.Product'),
        ),
        migrations.AddField(
            model_name='notification',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.State'),
        ),
        migrations.AddField(
            model_name='managecontent',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.State'),
        ),
        migrations.AddField(
            model_name='managecontent',
            name='user_id_admin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='district',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.State'),
        ),
    ]
