# Generated by Django 2.1.13 on 2019-10-18 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hurlapp', '0002_auto_20191018_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 10, 34, 29, 764849)),
        ),
        migrations.AlterField(
            model_name='city',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 10, 34, 29, 764884)),
        ),
        migrations.AlterField(
            model_name='district',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 10, 34, 29, 764230)),
        ),
        migrations.AlterField(
            model_name='district',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 10, 34, 29, 764254)),
        ),
        migrations.AlterField(
            model_name='language',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 10, 34, 29, 762968)),
        ),
        migrations.AlterField(
            model_name='language',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 10, 34, 29, 763001)),
        ),
        migrations.AlterField(
            model_name='loyaltypoints',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 10, 34, 29, 777459)),
        ),
        migrations.AlterField(
            model_name='loyaltypoints',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 10, 34, 29, 777500)),
        ),
        migrations.AlterField(
            model_name='managecontent',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 10, 34, 29, 770658)),
        ),
        migrations.AlterField(
            model_name='managecontent',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 10, 34, 29, 770425)),
        ),
        migrations.AlterField(
            model_name='managecontent',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 10, 34, 29, 770682)),
        ),
        migrations.AlterField(
            model_name='mobilelang',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 10, 34, 29, 775284)),
        ),
        migrations.AlterField(
            model_name='mobilelang',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 10, 34, 29, 775308)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 10, 34, 29, 771985)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 10, 34, 29, 772010)),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 10, 34, 29, 769673)),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 10, 34, 29, 769698)),
        ),
        migrations.AlterField(
            model_name='orderproductsdetail',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 10, 34, 29, 776776)),
        ),
        migrations.AlterField(
            model_name='orderproductsdetail',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 10, 34, 29, 776800)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 10, 34, 29, 768772)),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 10, 34, 29, 768798)),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 10, 34, 29, 774350)),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 10, 34, 29, 774374)),
        ),
        migrations.AlterField(
            model_name='scratch',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 10, 34, 29, 776034)),
        ),
        migrations.AlterField(
            model_name='scratch',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 10, 34, 29, 776058)),
        ),
        migrations.AlterField(
            model_name='state',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 10, 34, 29, 763625)),
        ),
        migrations.AlterField(
            model_name='state',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 10, 34, 29, 763651)),
        ),
        migrations.AlterField(
            model_name='support',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 10, 34, 29, 772845)),
        ),
        migrations.AlterField(
            model_name='support',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 10, 34, 29, 772945)),
        ),
        migrations.AlterField(
            model_name='supportreply',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 10, 34, 29, 773566)),
        ),
        migrations.AlterField(
            model_name='supportreply',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 10, 34, 29, 773591)),
        ),
        migrations.AlterField(
            model_name='userloyaltypoints',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 10, 34, 29, 778248)),
        ),
        migrations.AlterField(
            model_name='userloyaltypoints',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 10, 34, 29, 778272)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 10, 34, 29, 765821)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 10, 34, 29, 765846)),
        ),
    ]
