# Generated by Django 2.1.13 on 2019-11-02 06:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hurlapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 11, 2, 6, 11, 7, 912888))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 11, 2, 6, 11, 7, 912916))),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=255)),
                ('district_id', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 11, 2, 6, 11, 7, 912218))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 11, 2, 6, 11, 7, 912243))),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_name', models.CharField(max_length=255)),
                ('lang_code', models.CharField(max_length=150)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 11, 2, 6, 11, 7, 911077))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 11, 2, 6, 11, 7, 911107))),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loyalty_type', models.CharField(max_length=255)),
                ('loyalty_point', models.IntegerField()),
                ('conversion', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 11, 2, 6, 11, 7, 927141))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 11, 2, 6, 11, 7, 927166))),
            ],
        ),
        migrations.CreateModel(
            name='ManageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_eng', models.CharField(max_length=255)),
                ('title_hnd', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 11, 2, 6, 11, 7, 920130))),
                ('state_id', models.IntegerField(default=0)),
                ('district_id', models.IntegerField(default=0)),
                ('group_id', models.CharField(max_length=255)),
                ('contains_eng', models.TextField()),
                ('contains_hnd', models.TextField()),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 11, 2, 6, 11, 7, 920303))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 11, 2, 6, 11, 7, 920327))),
                ('feature_image', models.ImageField(blank=True, upload_to='media')),
                ('user_id_admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MobileLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_id', models.IntegerField()),
                ('lang_key', models.CharField(max_length=255)),
                ('lang_lab', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 11, 2, 6, 11, 7, 924826))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 11, 2, 6, 11, 7, 924850))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_eng', models.TextField()),
                ('message_hnd', models.TextField()),
                ('sms_status', models.IntegerField(default=0)),
                ('push_status', models.IntegerField(default=0)),
                ('sms_request', models.TextField()),
                ('push_request', models.TextField()),
                ('sms_response', models.TextField()),
                ('push_response', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 11, 2, 6, 11, 7, 921547))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 11, 2, 6, 11, 7, 921571))),
                ('status', models.IntegerField(default=1)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.District')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 11, 2, 6, 11, 7, 919385))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 11, 2, 6, 11, 7, 919412))),
                ('user_id_farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
                ('user_id_retailer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProductsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.IntegerField()),
                ('product_price', models.FloatField()),
                ('product_total_price', models.FloatField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 11, 2, 6, 11, 7, 926360))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 11, 2, 6, 11, 7, 926479))),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_code', models.CharField(max_length=100)),
                ('product_unit_name', models.CharField(blank=True, max_length=255)),
                ('product_unit', models.CharField(max_length=10)),
                ('product_price', models.FloatField(blank=True, null=True)),
                ('product_image', models.ImageField(blank=True, upload_to='media')),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 11, 2, 6, 11, 7, 918507))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 11, 2, 6, 11, 7, 918534))),
            ],
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 11, 2, 6, 11, 7, 913364))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 11, 2, 6, 11, 7, 913407))),
            ],
        ),
        migrations.CreateModel(
            name='Recharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=255)),
                ('transation_id', models.IntegerField()),
                ('transation_request', models.TextField()),
                ('transation_response', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 11, 2, 6, 11, 7, 924034))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 11, 2, 6, 11, 7, 924061))),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.Order')),
                ('user_id_farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user_auth_recharge', to=settings.AUTH_USER_MODEL)),
                ('user_id_retailer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user_auth_recharge', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scratch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 11, 2, 6, 11, 7, 925530))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 11, 2, 6, 11, 7, 925557))),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.Order')),
                ('user_id_farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user_auth', to=settings.AUTH_USER_MODEL)),
                ('user_id_retailer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user_auth', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 11, 2, 6, 11, 7, 911670))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 11, 2, 6, 11, 7, 911694))),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('query', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 11, 2, 6, 11, 7, 922505))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 11, 2, 6, 11, 7, 922530))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupportReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('query', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 11, 2, 6, 11, 7, 923222))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 11, 2, 6, 11, 7, 923251))),
                ('support_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.Support')),
                ('user_id_admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLinkage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 11, 2, 6, 11, 7, 913916))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 11, 2, 6, 11, 7, 913940))),
                ('status', models.IntegerField(default=1)),
                ('retailer_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user_retailer', to=settings.AUTH_USER_MODEL)),
                ('wholesaler_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user_wholsaler', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLoyaltyPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_user_id', models.IntegerField()),
                ('from_user_id', models.IntegerField()),
                ('loyalty_type', models.CharField(max_length=255)),
                ('loyalty_points_id', models.CharField(max_length=255)),
                ('order_id', models.IntegerField()),
                ('loyalty_point', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 11, 2, 6, 11, 7, 927904))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 11, 2, 6, 11, 7, 927929))),
                ('status', models.IntegerField(default=1)),
                ('user_id_farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user_auth_point', to=settings.AUTH_USER_MODEL)),
                ('user_id_retailer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user_auth_point', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField()),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('aadhar_no', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('user_photo', models.ImageField(blank=True, upload_to=hurlapp.models.get_image_filename)),
                ('aadhar_card', models.ImageField(blank=True, upload_to=hurlapp.models.get_image_filename)),
                ('pan_card', models.ImageField(blank=True, upload_to=hurlapp.models.get_image_filename)),
                ('vote_id', models.ImageField(blank=True, upload_to=hurlapp.models.get_image_filename)),
                ('soil_card', models.ImageField(blank=True, upload_to=hurlapp.models.get_image_filename)),
                ('fertilizer_photo', models.ImageField(blank=True, upload_to=hurlapp.models.get_image_filename)),
                ('gst_photo', models.ImageField(blank=True, upload_to=hurlapp.models.get_image_filename)),
                ('land_area', models.CharField(blank=True, max_length=255, null=True)),
                ('otp', models.CharField(blank=True, max_length=10, null=True)),
                ('fcm_id', models.TextField(blank=True, null=True)),
                ('fms_id', models.CharField(blank=True, max_length=255, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=255, null=True)),
                ('fertilizer_licence', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 11, 2, 6, 11, 7, 916289))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 11, 2, 6, 11, 7, 916320))),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.District')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.Language')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.State')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.AddField(
            model_name='orderproductsdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.Product'),
        ),
        migrations.AddField(
            model_name='notification',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.State'),
        ),
        migrations.AddField(
            model_name='district',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.State'),
        ),
    ]
