# Generated by Django 2.2.6 on 2019-10-09 08:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 9, 13, 59, 52, 848596))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 9, 13, 59, 52, 848596))),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=255)),
                ('district_id', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 9, 13, 59, 52, 848596))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 9, 13, 59, 52, 848596))),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_name', models.CharField(max_length=255)),
                ('lang_code', models.CharField(max_length=150)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 9, 13, 59, 52, 846600))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 9, 13, 59, 52, 846600))),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loyalty_type', models.CharField(max_length=255)),
                ('loyalty_point', models.IntegerField()),
                ('conversion', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 9, 13, 59, 52, 855577))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 9, 13, 59, 52, 855577))),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 9, 13, 59, 52, 850590))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 9, 13, 59, 52, 850590))),
                ('user_id_farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
                ('user_id_retailer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_code', models.CharField(max_length=100)),
                ('product_unit', models.CharField(max_length=10)),
                ('product_price', models.FloatField(blank=True, null=True)),
                ('product_image', models.ImageField(blank=True, upload_to='media')),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 9, 13, 59, 52, 850590))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 9, 13, 59, 52, 850590))),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 9, 13, 59, 52, 847598))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 9, 13, 59, 52, 847598))),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('query', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 9, 13, 59, 52, 852585))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 9, 13, 59, 52, 852585))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField()),
                ('aadhar_no', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('pincode', models.IntegerField()),
                ('address', models.TextField()),
                ('user_photo', models.ImageField(blank=True, upload_to='media')),
                ('aadhar_card', models.ImageField(blank=True, upload_to='media')),
                ('pan_card', models.ImageField(blank=True, upload_to='media')),
                ('vote_id', models.ImageField(blank=True, upload_to='media')),
                ('soil_card', models.ImageField(blank=True, upload_to='media')),
                ('land_area', models.CharField(max_length=255)),
                ('otp', models.CharField(max_length=10)),
                ('fcm_id', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 9, 13, 59, 52, 849593))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 9, 13, 59, 52, 849593))),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.District')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.Language')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.State')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='UserLoyaltyPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_user_id', models.IntegerField()),
                ('from_user_id', models.IntegerField()),
                ('loyalty_type', models.CharField(max_length=255)),
                ('loyalty_points_id', models.CharField(max_length=255)),
                ('order_id', models.IntegerField()),
                ('loyalty_point', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 9, 13, 59, 52, 855577))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 9, 13, 59, 52, 855577))),
                ('status', models.IntegerField(default=1)),
                ('user_id_farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user_auth_point', to=settings.AUTH_USER_MODEL)),
                ('user_id_retailer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user_auth_point', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupportReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('query', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 9, 13, 59, 52, 853582))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 9, 13, 59, 52, 853582))),
                ('support_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.Support')),
                ('user_id_admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scratch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 9, 13, 59, 52, 854579))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 9, 13, 59, 52, 854579))),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.Order')),
                ('user_id_farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user_auth', to=settings.AUTH_USER_MODEL)),
                ('user_id_retailer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user_auth', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=255)),
                ('transation_id', models.IntegerField()),
                ('transation_request', models.TextField()),
                ('transation_response', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 9, 13, 59, 52, 853582))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 9, 13, 59, 52, 853582))),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.Order')),
                ('user_id_farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user_auth_recharge', to=settings.AUTH_USER_MODEL)),
                ('user_id_retailer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user_auth_recharge', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProductsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.IntegerField()),
                ('product_price', models.FloatField()),
                ('product_total_price', models.FloatField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 9, 13, 59, 52, 854579))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 9, 13, 59, 52, 854579))),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_eng', models.TextField()),
                ('message_hnd', models.TextField()),
                ('sms_status', models.IntegerField(default=0)),
                ('push_status', models.IntegerField(default=0)),
                ('sms_request', models.TextField()),
                ('push_request', models.TextField()),
                ('sms_response', models.TextField()),
                ('push_response', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 9, 13, 59, 52, 851587))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 9, 13, 59, 52, 851587))),
                ('status', models.IntegerField(default=1)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.District')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.State')),
            ],
        ),
        migrations.CreateModel(
            name='MobileLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_id', models.IntegerField()),
                ('lang_key', models.CharField(max_length=255)),
                ('lang_lab', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 9, 13, 59, 52, 854579))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 9, 13, 59, 52, 854579))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_eng', models.CharField(max_length=255)),
                ('title_hnd', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 10, 9, 13, 59, 52, 851587))),
                ('contains_eng', models.TextField()),
                ('contains_hnd', models.TextField()),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 9, 13, 59, 52, 851587))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 9, 13, 59, 52, 851587))),
                ('feature_image', models.ImageField(blank=True, upload_to='media')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.District')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.State')),
                ('user_id_admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.State'),
        ),
    ]
