# Generated by Django 2.2.6 on 2019-10-24 11:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hurlapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 46, 732235))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 46, 732332))),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=255)),
                ('district_id', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 46, 730506))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 46, 730739))),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_name', models.CharField(max_length=255)),
                ('lang_code', models.CharField(max_length=150)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 46, 728397))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 46, 728449))),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loyalty_type', models.CharField(max_length=255)),
                ('loyalty_point', models.IntegerField()),
                ('conversion', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 46, 751422))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 46, 751448))),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 46, 739448))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 46, 739474))),
                ('user_id_farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
                ('user_id_retailer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_code', models.CharField(max_length=100)),
                ('product_unit_name', models.CharField(max_length=255)),
                ('product_unit', models.CharField(max_length=10)),
                ('product_price', models.FloatField(blank=True, null=True)),
                ('product_image', models.ImageField(blank=True, upload_to='media')),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 46, 738586))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 46, 738624))),
            ],
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 46, 734224))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 46, 734283))),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 46, 729529))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 46, 729560))),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('query', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 46, 743764))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 46, 743821))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField()),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('aadhar_no', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('user_photo', models.ImageField(blank=True, upload_to=hurlapp.models.get_image_filename)),
                ('aadhar_card', models.ImageField(blank=True, upload_to=hurlapp.models.get_image_filename)),
                ('pan_card', models.ImageField(blank=True, upload_to=hurlapp.models.get_image_filename)),
                ('vote_id', models.ImageField(blank=True, upload_to=hurlapp.models.get_image_filename)),
                ('soil_card', models.ImageField(blank=True, upload_to=hurlapp.models.get_image_filename)),
                ('fertilizer_photo', models.ImageField(blank=True, upload_to=hurlapp.models.get_image_filename)),
                ('land_area', models.CharField(blank=True, max_length=255, null=True)),
                ('otp', models.CharField(blank=True, max_length=10, null=True)),
                ('fcm_id', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 46, 736707))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 46, 736755))),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.District')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.Language')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.State')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='UserLoyaltyPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_user_id', models.IntegerField()),
                ('from_user_id', models.IntegerField()),
                ('loyalty_type', models.CharField(max_length=255)),
                ('loyalty_points_id', models.CharField(max_length=255)),
                ('order_id', models.IntegerField()),
                ('loyalty_point', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 46, 752108))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 46, 752137))),
                ('status', models.IntegerField(default=1)),
                ('user_id_farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user_auth_point', to=settings.AUTH_USER_MODEL)),
                ('user_id_retailer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user_auth_point', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLinkage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 46, 735118))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 46, 735186))),
                ('status', models.IntegerField(default=1)),
                ('retailer_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user_retailer', to=settings.AUTH_USER_MODEL)),
                ('wholesaler_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user_wholsaler', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupportReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('query', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 46, 744610))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 46, 744638))),
                ('support_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.Support')),
                ('user_id_admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scratch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 46, 748907))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 46, 748958))),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.Order')),
                ('user_id_farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user_auth', to=settings.AUTH_USER_MODEL)),
                ('user_id_retailer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user_auth', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=255)),
                ('transation_id', models.IntegerField()),
                ('transation_request', models.TextField()),
                ('transation_response', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 46, 745945))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 46, 745991))),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.Order')),
                ('user_id_farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user_auth_recharge', to=settings.AUTH_USER_MODEL)),
                ('user_id_retailer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user_auth_recharge', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProductsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.IntegerField()),
                ('product_price', models.FloatField()),
                ('product_total_price', models.FloatField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 46, 750384))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 46, 750430))),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_eng', models.TextField()),
                ('message_hnd', models.TextField()),
                ('sms_status', models.IntegerField(default=0)),
                ('push_status', models.IntegerField(default=0)),
                ('sms_request', models.TextField()),
                ('push_request', models.TextField()),
                ('sms_response', models.TextField()),
                ('push_response', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 46, 741758))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 46, 741788))),
                ('status', models.IntegerField(default=1)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.District')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.State')),
            ],
        ),
        migrations.CreateModel(
            name='MobileLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_id', models.IntegerField()),
                ('lang_key', models.CharField(max_length=255)),
                ('lang_lab', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 46, 747464))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 46, 747522))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_eng', models.CharField(max_length=255)),
                ('title_hnd', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 46, 740140))),
                ('contains_eng', models.TextField()),
                ('contains_hnd', models.TextField()),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 46, 740446))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 46, 740469))),
                ('feature_image', models.ImageField(blank=True, upload_to='media')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.District')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.State')),
                ('user_id_admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurlapp.State'),
        ),
    ]
