# Generated by Django 2.2.6 on 2019-10-24 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hurlapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 49, 560596)),
        ),
        migrations.AlterField(
            model_name='city',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 49, 560632)),
        ),
        migrations.AlterField(
            model_name='district',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 49, 559638)),
        ),
        migrations.AlterField(
            model_name='district',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 49, 559688)),
        ),
        migrations.AlterField(
            model_name='language',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 49, 557902)),
        ),
        migrations.AlterField(
            model_name='language',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 49, 557939)),
        ),
        migrations.AlterField(
            model_name='loyaltypoints',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 49, 573703)),
        ),
        migrations.AlterField(
            model_name='loyaltypoints',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 49, 573729)),
        ),
        migrations.AlterField(
            model_name='managecontent',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 49, 566883)),
        ),
        migrations.AlterField(
            model_name='managecontent',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 49, 566680)),
        ),
        migrations.AlterField(
            model_name='managecontent',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 49, 566904)),
        ),
        migrations.AlterField(
            model_name='mobilelang',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 49, 571456)),
        ),
        migrations.AlterField(
            model_name='mobilelang',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 49, 571485)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 49, 568140)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 49, 568167)),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 49, 565942)),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 49, 565968)),
        ),
        migrations.AlterField(
            model_name='orderproductsdetail',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 49, 572970)),
        ),
        migrations.AlterField(
            model_name='orderproductsdetail',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 49, 572996)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 49, 565125)),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 49, 565152)),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 49, 561290)),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 49, 561323)),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 49, 570643)),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 49, 570669)),
        ),
        migrations.AlterField(
            model_name='scratch',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 49, 572197)),
        ),
        migrations.AlterField(
            model_name='scratch',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 49, 572223)),
        ),
        migrations.AlterField(
            model_name='state',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 49, 558550)),
        ),
        migrations.AlterField(
            model_name='state',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 49, 558798)),
        ),
        migrations.AlterField(
            model_name='support',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 49, 569017)),
        ),
        migrations.AlterField(
            model_name='support',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 49, 569047)),
        ),
        migrations.AlterField(
            model_name='supportreply',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 49, 569697)),
        ),
        migrations.AlterField(
            model_name='supportreply',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 49, 569727)),
        ),
        migrations.AlterField(
            model_name='userlinkage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 49, 562097)),
        ),
        migrations.AlterField(
            model_name='userlinkage',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 49, 562128)),
        ),
        migrations.AlterField(
            model_name='userloyaltypoints',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 49, 574486)),
        ),
        migrations.AlterField(
            model_name='userloyaltypoints',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 49, 574513)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 49, 563288)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 11, 7, 49, 563315)),
        ),
    ]
