# Generated by Django 2.2.6 on 2019-10-09 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hurlapp', '0002_auto_20191009_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 10, 37, 19, 223256)),
        ),
        migrations.AlterField(
            model_name='city',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 10, 37, 19, 223276)),
        ),
        migrations.AlterField(
            model_name='district',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 10, 37, 19, 222798)),
        ),
        migrations.AlterField(
            model_name='district',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 10, 37, 19, 222818)),
        ),
        migrations.AlterField(
            model_name='language',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 10, 37, 19, 221889)),
        ),
        migrations.AlterField(
            model_name='language',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 10, 37, 19, 221917)),
        ),
        migrations.AlterField(
            model_name='loyaltypoints',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 10, 37, 19, 231435)),
        ),
        migrations.AlterField(
            model_name='loyaltypoints',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 10, 37, 19, 231459)),
        ),
        migrations.AlterField(
            model_name='managecontent',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 10, 37, 19, 226443)),
        ),
        migrations.AlterField(
            model_name='managecontent',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 10, 37, 19, 226290)),
        ),
        migrations.AlterField(
            model_name='managecontent',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 10, 37, 19, 226462)),
        ),
        migrations.AlterField(
            model_name='mobilelang',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 10, 37, 19, 229754)),
        ),
        migrations.AlterField(
            model_name='mobilelang',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 10, 37, 19, 229775)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 10, 37, 19, 227318)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 10, 37, 19, 227342)),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 10, 37, 19, 225797)),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 10, 37, 19, 225818)),
        ),
        migrations.AlterField(
            model_name='orderproductsdetail',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 10, 37, 19, 230902)),
        ),
        migrations.AlterField(
            model_name='orderproductsdetail',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 10, 37, 19, 230922)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 10, 37, 19, 225221)),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 10, 37, 19, 225242)),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 10, 37, 19, 229156)),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 10, 37, 19, 229176)),
        ),
        migrations.AlterField(
            model_name='scratch',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 10, 37, 19, 230333)),
        ),
        migrations.AlterField(
            model_name='scratch',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 10, 37, 19, 230353)),
        ),
        migrations.AlterField(
            model_name='state',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 10, 37, 19, 222299)),
        ),
        migrations.AlterField(
            model_name='state',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 10, 37, 19, 222320)),
        ),
        migrations.AlterField(
            model_name='support',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 10, 37, 19, 228042)),
        ),
        migrations.AlterField(
            model_name='support',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 10, 37, 19, 228063)),
        ),
        migrations.AlterField(
            model_name='supportreply',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 10, 37, 19, 228533)),
        ),
        migrations.AlterField(
            model_name='supportreply',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 10, 37, 19, 228554)),
        ),
        migrations.AlterField(
            model_name='userloyaltypoints',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 10, 37, 19, 231926)),
        ),
        migrations.AlterField(
            model_name='userloyaltypoints',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 10, 37, 19, 231949)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 10, 37, 19, 223901)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 10, 37, 19, 223923)),
        ),
    ]
