# Generated by Django 2.1.13 on 2019-11-02 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hurlapp', '0005_auto_20191102_0613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scratch',
            old_name='order_id',
            new_name='order',
        ),
        migrations.AddField(
            model_name='recharge',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 9, 25, 26, 571173)),
        ),
        migrations.AlterField(
            model_name='city',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 9, 25, 26, 571198)),
        ),
        migrations.AlterField(
            model_name='district',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 9, 25, 26, 570509)),
        ),
        migrations.AlterField(
            model_name='district',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 9, 25, 26, 570615)),
        ),
        migrations.AlterField(
            model_name='language',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 9, 25, 26, 569380)),
        ),
        migrations.AlterField(
            model_name='language',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 9, 25, 26, 569411)),
        ),
        migrations.AlterField(
            model_name='loyaltypoints',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 9, 25, 26, 585663)),
        ),
        migrations.AlterField(
            model_name='loyaltypoints',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 9, 25, 26, 585688)),
        ),
        migrations.AlterField(
            model_name='managecontent',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 9, 25, 26, 578515)),
        ),
        migrations.AlterField(
            model_name='managecontent',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 9, 25, 26, 578328)),
        ),
        migrations.AlterField(
            model_name='managecontent',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 9, 25, 26, 578601)),
        ),
        migrations.AlterField(
            model_name='mobilelang',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 9, 25, 26, 583105)),
        ),
        migrations.AlterField(
            model_name='mobilelang',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 9, 25, 26, 583130)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 9, 25, 26, 579734)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 9, 25, 26, 579760)),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 9, 25, 26, 577677)),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 9, 25, 26, 577702)),
        ),
        migrations.AlterField(
            model_name='orderproductsdetail',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 9, 25, 26, 584854)),
        ),
        migrations.AlterField(
            model_name='orderproductsdetail',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 9, 25, 26, 584879)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 9, 25, 26, 576692)),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 9, 25, 26, 576719)),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 9, 25, 26, 571764)),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 9, 25, 26, 571788)),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 9, 25, 26, 582289)),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 9, 25, 26, 582315)),
        ),
        migrations.AlterField(
            model_name='scratch',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 9, 25, 26, 583894)),
        ),
        migrations.AlterField(
            model_name='scratch',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 9, 25, 26, 583918)),
        ),
        migrations.AlterField(
            model_name='state',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 9, 25, 26, 569938)),
        ),
        migrations.AlterField(
            model_name='state',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 9, 25, 26, 569963)),
        ),
        migrations.AlterField(
            model_name='support',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 9, 25, 26, 580736)),
        ),
        migrations.AlterField(
            model_name='support',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 9, 25, 26, 580761)),
        ),
        migrations.AlterField(
            model_name='supportreply',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 9, 25, 26, 581489)),
        ),
        migrations.AlterField(
            model_name='supportreply',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 9, 25, 26, 581519)),
        ),
        migrations.AlterField(
            model_name='userlinkage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 9, 25, 26, 572282)),
        ),
        migrations.AlterField(
            model_name='userlinkage',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 9, 25, 26, 572307)),
        ),
        migrations.AlterField(
            model_name='userloyaltypoints',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 9, 25, 26, 586333)),
        ),
        migrations.AlterField(
            model_name='userloyaltypoints',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 9, 25, 26, 586359)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 9, 25, 26, 574496)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 9, 25, 26, 574527)),
        ),
    ]
