# Generated by Django 2.2.6 on 2019-10-16 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hurlapp', '0008_auto_20191016_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 6, 43, 48, 729764)),
        ),
        migrations.AlterField(
            model_name='city',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 6, 43, 48, 729794)),
        ),
        migrations.AlterField(
            model_name='district',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 6, 43, 48, 729131)),
        ),
        migrations.AlterField(
            model_name='district',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 6, 43, 48, 729156)),
        ),
        migrations.AlterField(
            model_name='language',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 6, 43, 48, 727776)),
        ),
        migrations.AlterField(
            model_name='language',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 6, 43, 48, 727809)),
        ),
        migrations.AlterField(
            model_name='loyaltypoints',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 6, 43, 48, 741137)),
        ),
        migrations.AlterField(
            model_name='loyaltypoints',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 6, 43, 48, 741163)),
        ),
        migrations.AlterField(
            model_name='managecontent',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 6, 43, 48, 734277)),
        ),
        migrations.AlterField(
            model_name='managecontent',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 6, 43, 48, 734083)),
        ),
        migrations.AlterField(
            model_name='managecontent',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 6, 43, 48, 734299)),
        ),
        migrations.AlterField(
            model_name='mobilelang',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 6, 43, 48, 738806)),
        ),
        migrations.AlterField(
            model_name='mobilelang',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 6, 43, 48, 738833)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 6, 43, 48, 735551)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 6, 43, 48, 735578)),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 6, 43, 48, 733370)),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 6, 43, 48, 733395)),
        ),
        migrations.AlterField(
            model_name='orderproductsdetail',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 6, 43, 48, 740404)),
        ),
        migrations.AlterField(
            model_name='orderproductsdetail',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 6, 43, 48, 740430)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 6, 43, 48, 732548)),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 6, 43, 48, 732575)),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 6, 43, 48, 737904)),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 6, 43, 48, 737980)),
        ),
        migrations.AlterField(
            model_name='scratch',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 6, 43, 48, 739605)),
        ),
        migrations.AlterField(
            model_name='scratch',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 6, 43, 48, 739632)),
        ),
        migrations.AlterField(
            model_name='state',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 6, 43, 48, 728539)),
        ),
        migrations.AlterField(
            model_name='state',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 6, 43, 48, 728568)),
        ),
        migrations.AlterField(
            model_name='support',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 6, 43, 48, 736407)),
        ),
        migrations.AlterField(
            model_name='support',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 6, 43, 48, 736434)),
        ),
        migrations.AlterField(
            model_name='supportreply',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 6, 43, 48, 737104)),
        ),
        migrations.AlterField(
            model_name='supportreply',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 6, 43, 48, 737131)),
        ),
        migrations.AlterField(
            model_name='userloyaltypoints',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 6, 43, 48, 741818)),
        ),
        migrations.AlterField(
            model_name='userloyaltypoints',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 6, 43, 48, 741846)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 6, 43, 48, 730707)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 6, 43, 48, 730733)),
        ),
    ]
